sudo: false
language: node_js
node_js:
  - '4'
  - '6'

env:
  - VUE="vue@1"
  - VUE="vue@2"

before_install:
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi

install:
  - npm install $VUE
  - npm install

after_success:
  - npm run report-coverage
